require('nvim-navic').setup({
  lsp = {
    auto_attach = true,
  },
  icons = {
    Array = '󰅪 ',
    Boolean = '󰋰 ',
    Class = '󰓸 ',
    Constant = '󰭸 ',
    Constructor = '󰆧 ',
    Enum = '󰆜 ',
    EnumMember = '󰆜 ',
    Event = '󱐌 ',
    Field = '󰆧 ',
    File = '󰈤 ',
    Function = '󰆧 ',
    Interface = ' ',
    Key = '󰷖 ',
    Method = '󰆧 ',
    Module = ' ',
    Namespace = ' ',
    Null = '󰋰 ',
    Number = '󱦒 ',
    Object = ' ',
    Operator = '󱖦 ',
    Package = '󰏗 ',
    Property = '󰯠 ',
    String = '󰭳 ',
    Struct = '󰌗 ',
    TypeParameter = '󱄽 ',
    Variable = '󰮄 ',
  },
  highlight = true,
  separator = '  ',
})
