#!/bin/sh
#    ______      __         _      __   Gabriel Moreno
#   / ____/___ _/ /_  _____(_)__  / /   ==============
#  / / __/ __ `/ __ \/ ___/ / _ \/ /    E-mail:   gantoreno@gmail.com
# / /_/ / /_/ / /_/ / /  / /  __/ /     Website:  https://gantoreno.com
# \____/\__,_/_.___/_/  /_/\___/_/      GitHub:   https://github.com/gantoreno
# 
# Blocks script

# Build some blocks {{{
for i in 3 9; do
  for j in $(seq 0 7); do
    printf "\033[${i}${j}m%s\033[0m" " ███ "
  done

  printf "\n"
done

printf "\n"
# }}}

