#!/usr/bin/env python3

#    ______      __         _      __   Gabriel Moreno
#   / ____/___ _/ /_  _____(_)__  / /   ==============
#  / / __/ __ `/ __ \/ ___/ / _ \/ /    E-mail:   gantoreno@gmail.com
# / /_/ / /_/ / /_/ / /  / /  __/ /     Website:  https://gantoreno.com
# \____/\__,_/_.___/_/  /_/\___/_/      GitHub:   https://github.com/gantoreno
# 
# Expand script

# Imports {{{
import iterm2
# }}}

# Expansion script {{{
async def main(connection):
    app = await iterm2.async_get_app(connection)
    window = app.current_window

    if window is not None:
        await window.async_set_frame(
            iterm2.Frame(
                origin=iterm2.Point(100, 30),
                size=iterm2.Size(1215, 815)
            )
        ) 

iterm2.run_until_complete(main)
# }}}

