#!/bin/sh

#    ______      __         _      __   Gabriel Moreno
#   / ____/___ _/ /_  _____(_)__  / /   ==============
#  / / __/ __ `/ __ \/ ___/ / _ \/ /    E-mail:   gantoreno@gmail.com
# / /_/ / /_/ / /_/ / /  / /  __/ /     Website:  https://gantoreno.com
# \____/\__,_/_.___/_/  /_/\___/_/      GitHub:   https://github.com/gantoreno
# 
# Expand script

# Expansion script {{{
osascript <<- EOF 
tell application "iTerm2"
  set bounds of front window to {115, 55, 1322, 865}
end tell
EOF
# }}}

