#!/usr/bin/env python
import sys
import math

_, ms = sys.argv

time = int(ms) 
unit = 'ms'

if int(ms) >= 1000:
    time = round(int(ms) / 1000)
    unit = 's'

if int(ms) >= 60000:
    time = round(int(ms) / 60000)
    unit = 'm'

if int(ms) >= 3600000:
    time = round(int(ms) / 3600000)
    unit = 'h'

print(f'{time}{unit}')
