#!/usr/bin/env python3

import os
import sys

repo = 'https://raw.githubusercontent.com/IQAndreas/markdown-licenses'
branch = 'master'
filenames = {
  'mit': 'mit.md',
  'gplv3': 'gnu-gpl-v3.0.md',
  'bsd2': 'bsd-2.md',
  'apache2': 'apache-v2.0.md',
}

if __name__ == '__main__':
  if len(sys.argv) < 2: 
    print("You must provide a valid license name")
    exit(1)
  
  _, license = sys.argv

  filename = filenames[license]

  if not filename:
    print("This license hasn't been registered yet")

  url = f'{repo}/{branch}/{filename}'

  os.system(f'wget {url} -O LICENSE.md')
