#!/bin/sh

cat << EOF | pbcopy
### 1) Describe the work done

- 

### 2) Other PULL REQUESTS (or other dependencies) required to be merged first?
 
- N/A
    
### 3) Developer Testing
- [x] **❗️I understand \`NEW TESTS\` should be added when adding new features**
   - [x] *_Did Not_* need to add new test
- [x] **I have locally tested the platform thoroughly**
- [x] **I successfully performed the following \`TESTING\`**
   - **Optional:** *Depending on Project & Environment*
   - [x] \`Functional\` Testing
   - [x] \`Smoke\` Tests in a Development Environment
   - [ ] \`E2E\` Tests
   - [ ] \`Unit\` Testing

### 4) Screenshots or Videos
EOF
