#!/bin/sh

#    ______      __         _      __   Gabriel Moreno
#   / ____/___ _/ /_  _____(_)__  / /   ==============
#  / / __/ __ `/ __ \/ ___/ / _ \/ /    E-mail:   gantoreno@gmail.com
# / /_/ / /_/ / /_/ / /  / /  __/ /     Website:  https://gantoreno.com
# \____/\__,_/_.___/_/  /_/\___/_/      GitHub:   https://github.com/gantoreno
# 
# Workspace script

# Usage function {{{
usage() {
  echo "Usage:"
  echo "  workspace up [options]"
  echo "  workspace down"
  echo "Options:"
  echo "  -s | --single  single layout (1 extra pane)"
  echo "  -d | --double  double layout (2 extra panes)"
  echo "  -t | --triple  triple layout (3 extra panes)"

  exit 1
}
# }}}

# Warning function {{{
warning() {
  echo "Warning:"
  echo "  $1"

  exit 1
}
# }}}

# Check for parameters & TMUX availability {{{
[[ -z $TMUX ]] && warning "Workspace will only work inside a TMUX session!"
[[ "$#" != "1" && "$#" != "2" ]] && usage
# }}}

# Execute commands {{{
case $1 in
  up)
    if [[ -z $(tmux show-option -g @workspace) ]]; then
      tmux set-option -g @workspace "yes"
    else
      warning "Cannot nest workspaces!"
    fi

    tmux split-window -v -p 25 

    case $2 in
      -s | --single)
        ;;
      -d | --double)
        tmux split-window -hb -p 50
        ;;
      -t | --triple)
        tmux split-window -hb -p 66
        tmux split-window -hb -p 50
        ;;
    esac

    tmux select-pane -t 2

    exit
    ;;
  down)
    if [[ ! -z $(tmux show-option -g @workspace) ]]; then
      tmux set -gu @workspace

      panes=$(tmux list-panes | wc -l | xargs)

      [[ $panes -eq 1 ]] && warning "Cannot teardown a workspace with only 1 pane!"

      for pane in $(seq $panes 2); do
        tmux kill-pane -t $pane
      done
    else
      warning "No workspace layout has been toggled!"
    fi

    exit
    ;;
  *)
    usage
    ;;
esac
# }}}

